S=set()
N=input("Enter the number: ")
S.add(int(N))
N=input("Enter the number: ")
S.add(int(N))
N=input("Enter the number: ")
S.add(int(N))
N=input("Enter the number: ")
S.add(int(N))
N=input("Enter the number: ")
S.add(int(N))
N=input("Enter the number: ")
S.add(int(N))
N=input("Enter the number: ")
S.add(int(N))
N=input("Enter the number: ")
S.add(int(N))

print(S)