-- INNER JOIN
CREATE TABLE Departments(
    DEPARTMENTID INT PRIMARY KEY,
    DEPARTMENTNAME VARCHAR(20)
)

CREATE TABLE Students(
    STUDENTID INT IDENTITY(1, 1) PRIMARY KEY,
    NAMES VARCHAR(20),
    DEPARTMENTID INT FOREIGN KEY
    REFERENCES Departments
)

INSERT INTO Departments(DEPARTMENTID, DEPARTMENTNAME)
VALUES
(101, 'CS'),
(102, 'DS'),
(103, 'AI')

INSERT INTO Students(NAMES, DEPARTMENTID)
VALUES
('Ali', 101),
('Sara', 102),
('Ahmad', 103),
('Umar', 102)

SELECT NAMES, DEPARTMENTNAME
FROM Students
INNER JOIN Departments
ON Students.DEPARTMENTID = Departments.DEPARTMENTID

-- LEFT JOIN
SELECT NAMES, DEPARTMENTNAME
FROM Students
LEFT JOIN Departments
ON Students.DEPARTMENTID = Departments.DEPARTMENTID;

-- RIGHT JOIN
SELECT NAMES, DEPARTMENTNAME
FROM Students
RIGHT JOIN Departments
ON Students.DEPARTMENTID = Departments.DEPARTMENTID;

